[package]
name = "gameap-web-monitoring"
version = "1.0.5"
edition = "2021"
authors = ["GameAP Community"]
description = "WebAssembly monitoring plugin for GameAP written in Rust"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
prost = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
